/**
 *
 * $Id$
 */
package relations.validation;

import org.eclipse.emf.common.util.EList;

import relations.Relation;
import relations.RelationType;

/**
 * A sample validator interface for {@link relations.RelationsModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationsModelValidator {
	boolean validate();

	boolean validateRelationTypes(EList<RelationType> value);
	boolean validateRelations(EList<Relation> value);
}
