/**
 *
 * $Id$
 */
package relations.validation;

import relations.Relation;
import relations.RelationObject;
import relations.RelationType;

/**
 * A sample validator interface for {@link relations.Relation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationValidator {
	boolean validate();

	boolean validateType(RelationType value);
	boolean validateOpposite(Relation value);
	boolean validateFrom(RelationObject value);
	boolean validateTo(RelationObject value);
	boolean validateBidirectional(boolean value);
}
