/**
 *
 * $Id$
 */
package glossary.validation;

import glossary.Glossary;
import glossary.GlossaryTerm;
import glossary.TermCategory;
import glossary.TermInfluenceProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link glossary.GlossaryTerm}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GlossaryTermValidator {
	boolean validate();

	boolean validateGlossary(Glossary value);
	boolean validateTerm(String value);
	boolean validateDefinition(String value);
	boolean validateSynonym(EList<GlossaryTerm> value);
	boolean validateOtherforms(EList<String> value);
	boolean validateTermcategory(EList<TermCategory> value);
	boolean validateTermproperty(TermInfluenceProperty value);
	boolean validateAntonym(EList<GlossaryTerm> value);
}
