/**
 *
 * $Id$
 */
package requirements.validation;

import requirements.ProcessRequirements;
import requirements.ProjectRequirements;
import requirements.SystemRequirements;

/**
 * A sample validator interface for {@link requirements.ReqRepository}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReqRepositoryValidator {
	boolean validate();

	boolean validateDescription(String value);
	boolean validateProjectReqSection(ProjectRequirements value);
	boolean validateProcessReqSection(ProcessRequirements value);
	boolean validateSystemReqSection(SystemRequirements value);
}
