/**
 *
 * $Id$
 */
package requirements.validation;

import glossary.GlossaryTerm;

import org.eclipse.emf.common.util.EList;

import requirements.ReqPriorityEnum;
import requirements.ReqRepository;
import requirements.ReqStatusEnum;

/**
 * A sample validator interface for {@link requirements.Requirement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequirementValidator {
	boolean validate();

	boolean validateSpecification(String value);
	boolean validatePriority(ReqPriorityEnum value);
	boolean validateStatus(ReqStatusEnum value);
	boolean validateUsesTerms(EList<GlossaryTerm> value);
	boolean validateRepository(ReqRepository value);
}
