/**
 *
 * $Id$
 */
package pcmarchoptions.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.pcm.allocation.AllocationContext;

/**
 * A sample validator interface for {@link pcmarchoptions.PCM_AllocateNeverTogether}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PCM_AllocateNeverTogetherValidator {
	boolean validate();

	boolean validateAllocationContexts(EList<AllocationContext> value);
}
